project = "Fast Trimesh"
copyright = "2022, Benjamin Bolte"
author = "Benjamin Bolte"
extensions = ["sphinx.ext.autosummary", "sphinx.ext.autodoc"]
templates_path = ["_templates"]
exclude_patterns = []
autosummary_generate = True
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
